name    	'puppet-pakiti'
version 	'1.0.0'
source 		'Github'
author 		'Jan Collijs'
license 	'GPL'
summary 	'This module manages the pakiti service'
description 	'Using this module the pakiti service will be maintained'
project_page 	'https://github.ugent.be/Universiteitsbibliotheek/pm_pakitit'
dependency 	'Universiteitsbibliotheek/motd', '>= 1.0.0'
